name: cypress
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'     
        required: true
        default: 'cypress'
      source:
        description: 'Source tar.gz'
        required: true
env:
  NODEJS_VERSION: 12
defaults:
  run:
    shell: bash

jobs:
  # @see https://github.com/cypress-io/github-action
  cypress:
    runs-on: ubuntu-20.04
    steps:
      - # the source code is ONLY used to to get the cypress tests
        name: Checkout the source code
        uses: actions/checkout@v2
        with: 
          repository: 'wifi-tally/wifi-tally'
          ref: "${{ github.event.inputs.branch }}"
          path: .
      - run: |
          wget -O "${{ github.event.inputs.source }}"
          FILE_NAME=$(basename "${{ github.event.inputs.source }}")
          DIR_NAME=$(basename "${{ github.event.inputs.source }}" ".tar.gz")

          mkdir "${DIR_NAME}"
          cd  "${DIR_NAME}"
          
          tar -xzf "../${FILE_NAME}"

          mv "hub" "${GITHUB_WORKSPACE}/dist-hub"
      - name: Use node.js ${{ env.NODEJS_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODEJS_VERSION }}
      - # this step also runs "npm ci" and takes care of caching
        name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          start: npm run start --prefix "${GITHUB_WORKSPACE}/dist-hub"-- --with-test
          wait-on: 'http://localhost:3000'
          working-directory: ./hub
          record: true
          tag: "node-${{ env.NODEJS_VERSION }}"
