name: cypress
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'     
        required: true
        default: 'cypress'
env:
  NODEJS_VERSION: 12
defaults:
  run:
    shell: bash

jobs:
  # @see https://github.com/cypress-io/github-action
  cypress:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
        with: 
          repository: 'wifi-tally/wifi-tally'
          ref: "${{ github.event.inputs.branch }}"
          path: .
      - name: Use node.js ${{ env.NODEJS_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODEJS_VERSION }}
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - run: npm ci
        working-directory: ./hub
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          install: false
          start: npm run cypress:backend, npm run start:frontend
          wait-on: 'http://localhost:3000, http://localhost:3001'
          working-directory: ./hub
          spec: cypress/integration/smoke.spec.ts


  
