name: build
on: [ "push" ]
defaults:
  run:
    shell: bash
jobs:
  # ###
  #  
  # Detect the version number to use
  # 
  # ###
  setup:
    runs-on: ubuntu-latest
    outputs:
      build_name: ${{ steps.calc.outputs.build_name }}
      author_name: ${{ steps.calc.outputs.author_name }}
      author_email: ${{ steps.calc.outputs.author_email }}
      committer_name: ${{ steps.calc.outputs.committer_name }}
      committer_email: ${{ steps.calc.outputs.committer_email }}
      is_head: ${{ steps.calc.outputs.is_head }}
      branch: ${{ steps.calc.outputs.branch }}
      is_release_tag: ${{ steps.calc.outputs.is_release_tag }}

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # don't shallow clone! We could not generate a nice build_name otherwise
      - name: Generate parameters
        id: calc
        run: |
          echo "::set-output name=build_name::$(git describe --tags --always)"
          echo "::set-output name=author_name::${{ github.event.commits[0].author.name }}"
          echo "::set-output name=author_email::${{ github.event.commits[0].author.email }}"
          echo "::set-output name=committer_name::${{ github.event.commits[0].committer.name }}"
          echo "::set-output name=committer_email::${{ github.event.commits[0].committer.email }}"
          echo "::set-output name=is_head::${{ github.event.commits[0].id == github.event.head_commit.id }}"
          echo "::set-output name=branch::"
          if [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            echo "::set-output name=branch::${GITHUB_REF:11}"
          fi
          echo "::set-output name=is_release_tag::false"
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            if [[ "${GITHUB_REF:10}" =~ ^v[0-9]+\.[0-9]+ ]]; then
              echo "::set-output name=is_release_tag::true"
            fi
          fi
        shell: bash # we use bash syntax, so this is VERY important
      - name: Log Environment
        run: |
          echo "event=${{ toJson(github.event) }}"
      - name: Output
        run: |
          echo "build_name=${{ steps.calc.outputs.build_name }}"
          echo "author_name=${{ steps.calc.outputs.author_name }}"
          echo "author_email=${{ steps.calc.outputs.author_email }}"
          echo "committer_name=${{ steps.calc.outputs.committer_name }}"
          echo "committer_email=${{ steps.calc.outputs.committer_email }}"
          echo "is_head=${{ steps.calc.outputs.is_head }}"
          echo "branch=${{ steps.calc.outputs.branch }}"
          echo "is_release_tag=${{ steps.calc.outputs.is_release_tag }}"
          
