name: build
on: [ "push" ]
defaults:
  run:
    shell: bash
jobs:
  # ###
  #  
  # Detect the version number to use
  # 
  # ###
  setup:
    runs-on: ubuntu-latest
    outputs:
      build_name: ${{ steps.calc.outputs.build_name }}
      author_name: ${{ steps.calc.outputs.author_name }}
      author_email: ${{ steps.calc.outputs.author_email }}
      committer_name: ${{ steps.calc.outputs.committer_name }}
      committer_email: ${{ steps.calc.outputs.committer_email }}

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # don't shallow clone! We could not generate a nice build_name otherwise
      - name: Generate parameters
        id: calc
        run: |
          BUILD_NAME=$(git describe --tags --always)
          AUTHOR_NAME="${{ github.event.commits[0].author.name }}"
          AUTHOR_EMAIL="${{ github.event.commits[0].author.email }}"
          COMMITTER_NAME="${{ github.event.commits[0].committer.name }}"
          COMMITTER_EMAIL="${{ github.event.commits[0].committer.email }}"

          echo "::set-output name=build_name::$BUILD_NAME"
          echo "::set-output name=author_name::$AUTHOR_NAME"
          echo "::set-output name=author_email::$AUTHOR_EMAIL"
          echo "::set-output name=commiter_name::$COMMITTER_NAME"
          echo "::set-output name=commiter_email::$COMMITTER_EMAIL"

          echo "build_name=$BUILD_NAME"
          echo "author_name=$AUTHOR_NAME"
          echo "author_email=$AUTHOR_EMAIL"
          echo "commiter_name=$COMMITTER_NAME"
          echo "commiter_email=$COMMITTER_EMAIL"
      - name: Log Environment
        run: |
          echo "event=${{ toJson(github.event) }}"