name: build
on: [ "push" ]
defaults:
  run:
    shell: bash
jobs:
  # ###
  #  
  # Detect the version number to use
  # 
  # ###
  setup:
    runs-on: ubuntu-latest
    outputs:
      build_name: ${{ steps.calc.outputs.build_name }}
      author_name: ${{ steps.calc.outputs.author_name }}
      author_email: ${{ steps.calc.outputs.author_email }}
      committer_name: ${{ steps.calc.outputs.committer_name }}
      committer_email: ${{ steps.calc.outputs.committer_email }}

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # don't shallow clone! We could not generate a nice build_name otherwise
      - name: Generate build_name
        id: calc
        run: |
          echo "::set-output name=build_name::$(git describe --tags --always)"
          echo "::set-output name=author_name::${{ github.event.commits[0].author.name }}"
          echo "::set-output name=author_email::${{ github.event.commits[0].author.email }}"
          echo "::set-output name=commiter_name::${{ github.event.commits[0].committer.name }}"
          echo "::set-output name=commiter_email::${{ github.event.commits[0].committer.email }}"
      - name: Log Environment
        run: |
          echo "event=${{ toJson(github.event) }}"
      - name: Output
        run: |
          echo "build_name=${{ steps.build_name.outputs.build_name }}"
          echo "author_name=${{ steps.build_name.outputs.author_name }}"
          echo "author_email=${{ steps.build_name.outputs.author_email }}"
          echo "committer_name=${{ steps.build_name.outputs.committer_name }}"
          echo "committer_email=${{ steps.build_name.outputs.committer_email }}"
          
